spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: 'mehdi'
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8083
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true


