spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: chihebrca2002@gmail.com
    default-encoding: UTF-8
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true





