spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/notification
    username: 'mehdi'
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
rabbitmq:
  exchanges:
    internal:internal.exchange
  queue:
    notification:notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key




