server:
  port: 8889
spring:

  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path= /api/v1/customer/**
          filters:
            name: AuthFilter

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /api/v1/product/** , /api/v1/category/**
          filters:
            name: AuthFilter

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path= /api/v1/review/**
          filters:
            name: AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path= /api/v1/auth

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 60000 # 86400000 # a day
  refresh-token:
    expiration: 604800000 # 7 days

