server:
  port: 8889
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path= /api/v1/customer/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /api/v1/product/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path= /api/v1/review/**


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
